### ISSUE TITLE
Prefab Missing Issue

### ISSUE THREAD

**Issue by Dhruvi05IF** [microsoft/MixedReality-QRCode-Sample#10] opened 2022-08-03 11:07 UTC
Hello Sir,

please help me to provide a solution for bellow issue.

QRCodeSample scene gives an error when try to upgrade the project in 2020.3.13 unity version. i will also installed Mixed Reality OpenXR Plugin and MixedReality ToolKit using mixed reality feature toolkit and Microsoft.MixedReality.QR but still the prefab scripts are missing.

issue is:- Axis and QRCodeManage prefab is missing 
![Error](https://user-images.githubusercontent.com/103554104/182593705-53d3a10b-2945-44ce-8158-63c132c97261.JPG)

**Comment by cheles** [comment] 2022-08-17 13:11
this is a duplicate of https://github.com/microsoft/MixedReality-QRCode-Sample/issues/4

**Comment by chgatla-microsoft** [comment] 2022-09-01 18:50
New update is made resolved this issue

**Closed by chgatla-microsoft** 2022-09-01 18:50 UTC
Labels: bug
